### ISSUE TITLE
Clock Resets after 24 hours.

### ISSUE THREAD

**Issue by meltdown-mp4** [angelolz1/CookieClickerRPC#2]
The "Time Elapsed" prompt resets after it reaches 24 hours.

**Comment by angelolz1** [comment]
Unfortunately, this is a Discord Rich Presence limitation. I was hoping that it would go beyond 24 hours when initially testing, but on the Rich Presence Visualizer, it does the same thing as well.

I was going to make the Time Elapsed show on the details/state section (where the bank and cps details are shown) but the Rich Presence status updates every few seconds instead of every second.
