### ISSUE TITLE
Discord RPC not showing

### ISSUE THREAD

**Issue by Smartich0ke** [angelolz1/CookieClickerRPC#4]
I have downloaded version 1.1 of this mod on my Macbook Pro running MacOS Big Sur 11.5.2. I ran the jar file like so:
`java -jar CookieClickerRPC-NonWindows-1.1.jar`
And the jar file automatically opens my default browser which is Firefox 98.0. Then I run the following in the javascript console:
`Game.LoadMod('https://angelolz.dev/mods/ccrpc/main.js');`
and the mod successfully loads.
But no game is detected in Discord rich presence. Any ideas on how to fix this?
Here is the java console output:
`[09:27:22] INFO   Cookie Clicker - Discord Rich Presence v1.1
Error in LSRegisterURL: -10811
[09:27:22] INFO   Attempting to open Cookie Clicker website...
[09:27:22] INFO   Opened website.
[09:27:22] INFO   Server successfully started.
[09:27:42] INFO   Opened a connection with Cookie Clicker.`
Discord version is 0.0.265

**Comment by angelolz1** [comment]
Hey there! I have found the source of the problem.

One of the dependencies that I used to make this work is Vatuu's [`discord-rpc`](https://github.com/Vatuu/discord-rpc) library.

What I failed to realize is that the OSX / macOS support has been broken and this library has not been updated since. So basically, this app is currently not supported on macOS if you're playing the browser version. I'm sorry for the inconvenience.

I will try and see if I can find a way to get it working for macOS / OSX devices. If I do, I will make an update to this mod. Thank you very much for your report!

**Comment by Smartich0ke** [comment]
All good mate. Hope you find a solution soon! 👍

**Comment by angelolz1** [comment]
Hey there! Just wanted to let you know I've updated the client to support macOS devices. Check it out [here](https://github.com/angelolz1/CookieClickerRPC/releases/tag/v1.2) and let me know if you still have any issues. Thank you!

**Comment by Smartich0ke** [comment]
Thanks so much! I'll try it out soon.
